name: Build and Deploy Fullstack App to Render

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Install dependencies & build Vue
        working-directory: ./project
        run: |
          npm install
          npm run build

      - name: Copy frontend dist to Spring Boot static
        run: |
          mkdir -p ./manufacturing_system/src/main/resources/static
          rm -rf ./manufacturing_system/src/main/resources/static/*
          cp -r ./project/dist/* ./manufacturing_system/src/main/resources/static/

      - name: Build Spring Boot backend
        working-directory: ./manufacturing_system
        run: mvn clean package -DskipTests

      - name: Check jar file
        run: ls -l manufacturing_system/target/

      - name: Build Docker image
        working-directory: ./manufacturing_system
        run: docker build -t fullstack-app .

      - name: Trigger Render Deploy Hook
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}